// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type Auth struct {
	Token string `json:"token"`
}

type LoginMobilePassRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginRequest struct {
	UserId   string `json:"userId"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type RegisterRequest struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	Mobile     string `json:"mobile"`
	VerifyCode string `json:"verifyCode"`
}

type RegisterResponse struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type UserInfoResponse struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
	Type     string `json:"type"`
}

type VerifyCodeRequest struct {
	Mobile string `json:"mobile"`
}

type VerifyCodeResponse struct {
	Status string `json:"status"`
}
