// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AdminRes struct {
	Status   string `json:"status"`
	Operator string `json:"operator"`
}

type Article struct {
	Id          uint64 `db:"id"`          // 主键ID
	Title       string `db:"title"`       // 标题
	Content     string `db:"content"`     // 内容
	Media       string `db:"media"`       // 媒体资源
	Description string `db:"description"` // 描述
	AuthorId    uint64 `db:"author_id"`   // 作者ID
	Status      int64  `db:"status"`      // 状态 0:待审核 1:审核不通过 2:可见 3:用户删除
	Type        int64  `db:"type"`        // 状态 0:默认图片帧 1:视频帧 2:纯文字帧
	CommentNum  int64  `db:"comment_num"` // 评论数
	LikeNum     int64  `db:"like_num"`    // 点赞数
	CollectNum  int64  `db:"collect_num"` // 收藏数
	ViewNum     int64  `db:"view_num"`    // 浏览数
	ShareNum    int64  `db:"share_num"`   // 分享数
	TagIds      string `db:"tag_ids"`     // 标签ID
	User        string `db:"user"`
}

type Auth struct {
	Token string `json:"token"`
}

type ChangeMobileRequest struct {
	OldMobile  string `json:"oldMobile"`
	NewMobile  string `json:"newMobile"`
	VerifyCode string `json:"verifyCode"`
}

type ChangeMobileResponse struct {
	Status string `json:"status"`
}

type ChangePasswordRequest struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type ChangePasswordResponse struct {
	Status string `json:"status"`
}

type ChangeUserInfoRequest struct {
	Nickname  string `db:"nickname"`  // 昵称
	Signature string `db:"signature"` // 简介
	Avatar    string `db:"avatar"`    // 头像
}

type ChangeUserInfoResponse struct {
	Status string `json:"status"`
}

type ChangeUserTypeRequest struct {
	UserId string `json:"user_id"`
	Type   uint8  `json:"type"`
}

type DeleteArticleRequest struct {
	Id uint64 `json:"id"`
}

type Feed struct {
	Title     string    `json:"title"`
	Id        uint64    `json:"id"`
	MediaUrl  string    `json:"media_url"`
	MediaInfo MediaInfo `json:"media"`
	ViewNum   uint32    `json:"view_num"`
	LikeNum   uint32    `json:"like_num"`
	Loaded    bool      `json:"loaded"`
	User      FeedUser  `json:"user"`
}

type FeedUser struct {
	Id       uint64 `json:"id"`
	UserName string `json:"user_name"`
	Avatar   string `json:"avatar"`
}

type FollowListResponse struct {
	Message    string `json:"message"`
	FollowList []User `json:"followList"`
}

type FollowRequest struct {
	UserId string `json:"userId"`
}

type FollowResponse struct {
	Message string `json:"message"`
}

type GetIndexFeedsRequest struct {
	Offset uint64 `json:"offset"`
	Query  string `json:"query"`
}

type GetIndexFeedsResponse struct {
	Status string `json:"status"`
	Feeds  []Feed `json:"feeds"`
}

type LoginMobilePassRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginRequest struct {
	UserId   uint64 `json:"userId"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserId uint64 `json:"userId"`
	Token  string `json:"token"`
}

type MediaInfo struct {
	Width  uint32 `json:"width"`
	Height uint32 `json:"height"`
}

type NewArticleRequest struct {
	Title       string   `json:"title"`       // 标题
	Content     string   `json:"content"`     // 内容
	Media       []string `json:"媒体资源"`        // 封面
	Description string   `json:"description"` // 描述
}

type RegisterRequest struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	Mobile     string `json:"mobile"`
	VerifyCode string `json:"verifyCode"`
}

type RegisterResponse struct {
	UserId uint64 `json:"userId"`
	Token  string `json:"token"`
}

type SearchArticleRequest struct {
	Title  string `json:"title"`
	Author string `json:"author"`
	Tag    string `json:"tag"`
}

type SearchArticleResponse struct {
	Articles []Article `json:"articles"`
}

type StatusResponse struct {
	Status string `json:"status"`
}

type User struct {
	Nickname  string `db:"nickname"`  // 昵称
	Signature string `db:"signature"` // 简介
	Avatar    string `db:"avatar"`    // 头像
	Type      uint8  `db:"type"`      // 状态 0:默认用户 1:正式用户 2:V认证用户 3:管理员用户
}

type UserInfoResponse struct {
	UserId   uint64 `json:"userId"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
	Type     uint8  `json:"type"`
	Status   uint8  `json:"status"`
}

type VerifyCodeRequest struct {
	Mobile string `json:"mobile"`
}

type VerifyCodeResponse struct {
	Status string `json:"status"`
}
