// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package user_action

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userActionFieldNames          = builder.RawFieldNames(&UserAction{})
	userActionRows                = strings.Join(userActionFieldNames, ",")
	userActionRowsExpectAutoSet   = strings.Join(stringx.Remove(userActionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userActionRowsWithPlaceHolder = strings.Join(stringx.Remove(userActionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKeyframeUserActionIdPrefix                       = "cache:keyframe:userAction:id:"
	cacheKeyframeUserActionUserIdTargetIdActionTypePrefix = "cache:keyframe:userAction:userId:targetId:actionType:"
)

type (
	userActionModel interface {
		Insert(ctx context.Context, data *UserAction) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserAction, error)
		FindOneByUserIdTargetIdActionType(ctx context.Context, userId uint64, targetId uint64, actionType int64) (*UserAction, error)
		Update(ctx context.Context, data *UserAction) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserActionModel struct {
		sqlc.CachedConn
		table string
	}

	UserAction struct {
		Id          uint64    `db:"id"`
		UserId      uint64    `db:"user_id"`      // 用户ID
		TargetId    uint64    `db:"target_id"`    // 操作目标ID（文章/评论/用户等）
		ActionType  int64     `db:"action_type"`  // 操作类型：1-动态点赞, 2-评论点赞, 3-收藏, 4-关注
		TargetType  int64     `db:"target_type"`  // 目标类型：1-文章, 2-评论, 3-用户
		ActionValue int64     `db:"action_value"` // 操作值（1-执行，0-取消）
		CreateTime  time.Time `db:"create_time"`
		UpdateTime  time.Time `db:"update_time"`
	}
)

func newUserActionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserActionModel {
	return &defaultUserActionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_action`",
	}
}

func (m *defaultUserActionModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	keyframeUserActionIdKey := fmt.Sprintf("%s%v", cacheKeyframeUserActionIdPrefix, id)
	keyframeUserActionUserIdTargetIdActionTypeKey := fmt.Sprintf("%s%v:%v:%v", cacheKeyframeUserActionUserIdTargetIdActionTypePrefix, data.UserId, data.TargetId, data.ActionType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, keyframeUserActionIdKey, keyframeUserActionUserIdTargetIdActionTypeKey)
	return err
}

func (m *defaultUserActionModel) FindOne(ctx context.Context, id uint64) (*UserAction, error) {
	keyframeUserActionIdKey := fmt.Sprintf("%s%v", cacheKeyframeUserActionIdPrefix, id)
	var resp UserAction
	err := m.QueryRowCtx(ctx, &resp, keyframeUserActionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userActionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserActionModel) FindOneByUserIdTargetIdActionType(ctx context.Context, userId uint64, targetId uint64, actionType int64) (*UserAction, error) {
	keyframeUserActionUserIdTargetIdActionTypeKey := fmt.Sprintf("%s%v:%v:%v", cacheKeyframeUserActionUserIdTargetIdActionTypePrefix, userId, targetId, actionType)
	var resp UserAction
	err := m.QueryRowIndexCtx(ctx, &resp, keyframeUserActionUserIdTargetIdActionTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `target_id` = ? and `action_type` = ? limit 1", userActionRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, targetId, actionType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserActionModel) Insert(ctx context.Context, data *UserAction) (sql.Result, error) {
	keyframeUserActionIdKey := fmt.Sprintf("%s%v", cacheKeyframeUserActionIdPrefix, data.Id)
	keyframeUserActionUserIdTargetIdActionTypeKey := fmt.Sprintf("%s%v:%v:%v", cacheKeyframeUserActionUserIdTargetIdActionTypePrefix, data.UserId, data.TargetId, data.ActionType)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userActionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.TargetId, data.ActionType, data.TargetType, data.ActionValue)
	}, keyframeUserActionIdKey, keyframeUserActionUserIdTargetIdActionTypeKey)
	return ret, err
}

func (m *defaultUserActionModel) Update(ctx context.Context, newData *UserAction) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	keyframeUserActionIdKey := fmt.Sprintf("%s%v", cacheKeyframeUserActionIdPrefix, data.Id)
	keyframeUserActionUserIdTargetIdActionTypeKey := fmt.Sprintf("%s%v:%v:%v", cacheKeyframeUserActionUserIdTargetIdActionTypePrefix, data.UserId, data.TargetId, data.ActionType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userActionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.TargetId, newData.ActionType, newData.TargetType, newData.ActionValue, newData.Id)
	}, keyframeUserActionIdKey, keyframeUserActionUserIdTargetIdActionTypeKey)
	return err
}

func (m *defaultUserActionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKeyframeUserActionIdPrefix, primary)
}

func (m *defaultUserActionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userActionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserActionModel) tableName() string {
	return m.table
}
