// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.6

package user_action

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userActionFieldNames          = builder.RawFieldNames(&UserAction{}, true)
	userActionRows                = strings.Join(userActionFieldNames, ",")
	userActionRowsExpectAutoSet   = strings.Join(stringx.Remove(userActionFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	userActionRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(userActionFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicUserActionIdPrefix                       = "cache:public:userAction:id:"
	cachePublicUserActionUserIdTargetIdActionTypePrefix = "cache:public:userAction:userId:targetId:actionType:"
)

type (
	userActionModel interface {
		Insert(ctx context.Context, data *UserAction) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserAction, error)
		FindOneByUserIdTargetIdActionType(ctx context.Context, userId int64, targetId int64, actionType int64) (*UserAction, error)
		Update(ctx context.Context, data *UserAction) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserActionModel struct {
		sqlc.CachedConn
		table string
	}

	UserAction struct {
		Id          int64     `db:"id"`
		UserId      int64     `db:"user_id"`      // 用户ID
		TargetId    int64     `db:"target_id"`    // 操作目标ID（文章/评论/用户等）
		ActionType  int64     `db:"action_type"`  // 操作类型：1-动态点赞, 2-评论点赞, 3-收藏, 4-关注
		TargetType  int64     `db:"target_type"`  // 目标类型：1-文章, 2-评论, 3-用户
		ActionValue int64     `db:"action_value"` // 操作值（1-执行，0-取消）
		CreateTime  time.Time `db:"create_time"`
		UpdateTime  time.Time `db:"update_time"`
	}
)

func newUserActionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserActionModel {
	return &defaultUserActionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."user_action"`,
	}
}

func (m *defaultUserActionModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	publicUserActionIdKey := fmt.Sprintf("%s%v", cachePublicUserActionIdPrefix, id)
	publicUserActionUserIdTargetIdActionTypeKey := fmt.Sprintf("%s%v:%v:%v", cachePublicUserActionUserIdTargetIdActionTypePrefix, data.UserId, data.TargetId, data.ActionType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicUserActionIdKey, publicUserActionUserIdTargetIdActionTypeKey)
	return err
}

func (m *defaultUserActionModel) FindOne(ctx context.Context, id int64) (*UserAction, error) {
	publicUserActionIdKey := fmt.Sprintf("%s%v", cachePublicUserActionIdPrefix, id)
	var resp UserAction
	err := m.QueryRowCtx(ctx, &resp, publicUserActionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", userActionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserActionModel) FindOneByUserIdTargetIdActionType(ctx context.Context, userId int64, targetId int64, actionType int64) (*UserAction, error) {
	publicUserActionUserIdTargetIdActionTypeKey := fmt.Sprintf("%s%v:%v:%v", cachePublicUserActionUserIdTargetIdActionTypePrefix, userId, targetId, actionType)
	var resp UserAction
	err := m.QueryRowIndexCtx(ctx, &resp, publicUserActionUserIdTargetIdActionTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where user_id = $1 and target_id = $2 and action_type = $3 limit 1", userActionRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, targetId, actionType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserActionModel) Insert(ctx context.Context, data *UserAction) (sql.Result, error) {
	publicUserActionIdKey := fmt.Sprintf("%s%v", cachePublicUserActionIdPrefix, data.Id)
	publicUserActionUserIdTargetIdActionTypeKey := fmt.Sprintf("%s%v:%v:%v", cachePublicUserActionUserIdTargetIdActionTypePrefix, data.UserId, data.TargetId, data.ActionType)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, userActionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.TargetId, data.ActionType, data.TargetType, data.ActionValue)
	}, publicUserActionIdKey, publicUserActionUserIdTargetIdActionTypeKey)
	return ret, err
}

func (m *defaultUserActionModel) Update(ctx context.Context, newData *UserAction) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	publicUserActionIdKey := fmt.Sprintf("%s%v", cachePublicUserActionIdPrefix, data.Id)
	publicUserActionUserIdTargetIdActionTypeKey := fmt.Sprintf("%s%v:%v:%v", cachePublicUserActionUserIdTargetIdActionTypePrefix, data.UserId, data.TargetId, data.ActionType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, userActionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.TargetId, newData.ActionType, newData.TargetType, newData.ActionValue)
	}, publicUserActionIdKey, publicUserActionUserIdTargetIdActionTypeKey)
	return err
}

func (m *defaultUserActionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicUserActionIdPrefix, primary)
}

func (m *defaultUserActionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", userActionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserActionModel) tableName() string {
	return m.table
}
