// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package comment

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentFieldNames          = builder.RawFieldNames(&Comment{}, true)
	commentRows                = strings.Join(commentFieldNames, ",")
	commentRowsExpectAutoSet   = strings.Join(stringx.Remove(commentFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	commentRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(commentFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	publicCommentIdPrefix = ":public:comment:id:"
)

type (
	commentModel interface {
		Insert(ctx context.Context, data *Comment) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Comment, error)
		Update(ctx context.Context, data *Comment) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCommentModel struct {
		sqlc.CachedConn
		table string
	}

	Comment struct {
		Id           int64     `db:"id"`             // 主键ID
		ArticleId    int64     `db:"article_id"`     // 归属文章ID
		TargetId     int64     `db:"target_id"`      // 评论目标id，为0则回复文章
		TargetUserId int64     `db:"target_user_id"` // 被回复用户ID，为-1则无被回复id
		UserId       int64     `db:"user_id"`        // 评论用户ID
		Content      string    `db:"content"`        // 内容
		LikeNum      int64     `db:"like_num"`       // 点赞数
		Status       int64     `db:"status"`         // 状态 0:正常 1:删除
		Insp         int64     `db:"insp"`           // 人工校验为0时可用，默认为1待检验
		AiInsp       int64     `db:"ai_insp"`        // AI检验，默认0没有问题，1出现问题。
		IpLocation   string    `db:"ip_location"`    // IP归属地
		CreateTime   time.Time `db:"create_time"`    // 创建时间
		UpdateTime   time.Time `db:"update_time"`    // 最后修改时间
	}
)

func newCommentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCommentModel {
	return &defaultCommentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."comment"`,
	}
}

func (m *defaultCommentModel) Delete(ctx context.Context, id int64) error {
	publicCommentIdKey := fmt.Sprintf("%s%v", publicCommentIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicCommentIdKey)
	return err
}

func (m *defaultCommentModel) FindOne(ctx context.Context, id int64) (*Comment, error) {
	publicCommentIdKey := fmt.Sprintf("%s%v", publicCommentIdPrefix, id)
	var resp Comment
	err := m.QueryRowCtx(ctx, &resp, publicCommentIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", commentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentModel) Insert(ctx context.Context, data *Comment) (sql.Result, error) {
	publicCommentIdKey := fmt.Sprintf("%s%v", publicCommentIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, commentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ArticleId, data.TargetId, data.TargetUserId, data.UserId, data.Content, data.LikeNum, data.Status, data.Insp, data.AiInsp, data.IpLocation)
	}, publicCommentIdKey)
	return ret, err
}

func (m *defaultCommentModel) Update(ctx context.Context, data *Comment) error {
	publicCommentIdKey := fmt.Sprintf("%s%v", publicCommentIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, commentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.ArticleId, data.TargetId, data.TargetUserId, data.UserId, data.Content, data.LikeNum, data.Status, data.Insp, data.AiInsp, data.IpLocation)
	}, publicCommentIdKey)
	return err
}

func (m *defaultCommentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", publicCommentIdPrefix, primary)
}

func (m *defaultCommentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", commentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCommentModel) tableName() string {
	return m.table
}
