// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package notifications

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	notificationsFieldNames          = builder.RawFieldNames(&Notifications{}, true)
	notificationsRows                = strings.Join(notificationsFieldNames, ",")
	notificationsRowsExpectAutoSet   = strings.Join(stringx.Remove(notificationsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	notificationsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(notificationsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	publicNotificationsIdPrefix = ":public:notifications:id:"
)

type (
	notificationsModel interface {
		Insert(ctx context.Context, data *Notifications) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Notifications, error)
		Update(ctx context.Context, data *Notifications) error
		Delete(ctx context.Context, id int64) error
	}

	defaultNotificationsModel struct {
		sqlc.CachedConn
		table string
	}

	Notifications struct {
		Id         int64          `db:"id"`          // 主键，自增 ID
		SenderId   sql.NullInt64  `db:"sender_id"`   // 发送人 ID，系统通知可为 NULL
		ReceiverId int64          `db:"receiver_id"` // 接收人 ID
		Type       string         `db:"type"`        // 通知类型，例如 system、follow、like、favorite、comment
		Content    sql.NullString `db:"content"`     // 通知显示内容，可用于消息列表展示
		TargetType sql.NullString `db:"target_type"` // 通知对象的类型，如 post、comment、user
		TargetId   sql.NullInt64  `db:"target_id"`   // 通知对象的 ID
		IsRead     bool           `db:"is_read"`     // 是否已读标志
		CreateTime time.Time      `db:"create_time"` // 通知创建时间
		Extra      string         `db:"extra"`       // 额外信息（JSON 格式），如帖子标题、评论摘要等
	}
)

func newNotificationsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultNotificationsModel {
	return &defaultNotificationsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."notifications"`,
	}
}

func (m *defaultNotificationsModel) Delete(ctx context.Context, id int64) error {
	publicNotificationsIdKey := fmt.Sprintf("%s%v", publicNotificationsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicNotificationsIdKey)
	return err
}

func (m *defaultNotificationsModel) FindOne(ctx context.Context, id int64) (*Notifications, error) {
	publicNotificationsIdKey := fmt.Sprintf("%s%v", publicNotificationsIdPrefix, id)
	var resp Notifications
	err := m.QueryRowCtx(ctx, &resp, publicNotificationsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", notificationsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNotificationsModel) Insert(ctx context.Context, data *Notifications) (sql.Result, error) {
	publicNotificationsIdKey := fmt.Sprintf("%s%v", publicNotificationsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, notificationsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SenderId, data.ReceiverId, data.Type, data.Content, data.TargetType, data.TargetId, data.IsRead, data.Extra)
	}, publicNotificationsIdKey)
	return ret, err
}

func (m *defaultNotificationsModel) Update(ctx context.Context, data *Notifications) error {
	publicNotificationsIdKey := fmt.Sprintf("%s%v", publicNotificationsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, notificationsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.SenderId, data.ReceiverId, data.Type, data.Content, data.TargetType, data.TargetId, data.IsRead, data.Extra)
	}, publicNotificationsIdKey)
	return err
}

func (m *defaultNotificationsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", publicNotificationsIdPrefix, primary)
}

func (m *defaultNotificationsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", notificationsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultNotificationsModel) tableName() string {
	return m.table
}
