// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package report

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	reportFieldNames          = builder.RawFieldNames(&Report{}, true)
	reportRows                = strings.Join(reportFieldNames, ",")
	reportRowsExpectAutoSet   = strings.Join(stringx.Remove(reportFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	reportRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(reportFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	publicReportIdPrefix = ":public:report:id:"
)

type (
	reportModel interface {
		Insert(ctx context.Context, data *Report) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Report, error)
		Update(ctx context.Context, data *Report) error
		Delete(ctx context.Context, id int64) error
	}

	defaultReportModel struct {
		sqlc.CachedConn
		table string
	}

	Report struct {
		Id             int64     `db:"id"`               // 举报记录的唯一自增标识符
		ReportedId     int64     `db:"reported_id"`      // 被举报对象的 ID
		ReportedType   int64     `db:"reported_type"`    // 被举报对象的类型，1: 用户, 2: 文章, 3: 评论
		ReporterUserId int64     `db:"reporter_user_id"` // 举报用户的 ID
		CreateTime     time.Time `db:"create_time"`      // 举报记录的创建时间
		UpdateTime     time.Time `db:"update_time"`      // 举报记录的更新时间
		ReportType     int64     `db:"report_type"`      // 举报类型，1: 色情, 2: 骚扰, 3: 广告, 4: 政治, 5: 引战, 6: 辱骂, 7: 其他
		IsProcessed    bool      `db:"is_processed"`     // 举报是否已处理，默认为否
		OwnerId        int64     `db:"owner_id"`         // 被举报用户ID
	}
)

func newReportModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultReportModel {
	return &defaultReportModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."report"`,
	}
}

func (m *defaultReportModel) Delete(ctx context.Context, id int64) error {
	publicReportIdKey := fmt.Sprintf("%s%v", publicReportIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicReportIdKey)
	return err
}

func (m *defaultReportModel) FindOne(ctx context.Context, id int64) (*Report, error) {
	publicReportIdKey := fmt.Sprintf("%s%v", publicReportIdPrefix, id)
	var resp Report
	err := m.QueryRowCtx(ctx, &resp, publicReportIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", reportRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReportModel) Insert(ctx context.Context, data *Report) (sql.Result, error) {
	publicReportIdKey := fmt.Sprintf("%s%v", publicReportIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, reportRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ReportedId, data.ReportedType, data.ReporterUserId, data.ReportType, data.IsProcessed, data.OwnerId)
	}, publicReportIdKey)
	return ret, err
}

func (m *defaultReportModel) Update(ctx context.Context, data *Report) error {
	publicReportIdKey := fmt.Sprintf("%s%v", publicReportIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, reportRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.ReportedId, data.ReportedType, data.ReporterUserId, data.ReportType, data.IsProcessed, data.OwnerId)
	}, publicReportIdKey)
	return err
}

func (m *defaultReportModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", publicReportIdPrefix, primary)
}

func (m *defaultReportModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", reportRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultReportModel) tableName() string {
	return m.table
}
