// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package tag

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tagFieldNames          = builder.RawFieldNames(&Tag{})
	tagRows                = strings.Join(tagFieldNames, ",")
	tagRowsExpectAutoSet   = strings.Join(stringx.Remove(tagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tagRowsWithPlaceHolder = strings.Join(stringx.Remove(tagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheChaozjTagIdPrefix = "cache:chaozj:tag:id:"
)

type (
	tagModel interface {
		Insert(ctx context.Context, data *Tag) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Tag, error)
		Update(ctx context.Context, data *Tag) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTagModel struct {
		sqlc.CachedConn
		table string
	}

	Tag struct {
		Id         uint64    `db:"id"`          // 主键ID
		TagName    string    `db:"tag_name"`    // 标签名
		TagDesc    string    `db:"tag_desc"`    // 标签描述
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 最后修改时间
	}
)

func newTagModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTagModel {
	return &defaultTagModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tag`",
	}
}

func (m *defaultTagModel) Delete(ctx context.Context, id uint64) error {
	chaozjTagIdKey := fmt.Sprintf("%s%v", cacheChaozjTagIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, chaozjTagIdKey)
	return err
}

func (m *defaultTagModel) FindOne(ctx context.Context, id uint64) (*Tag, error) {
	chaozjTagIdKey := fmt.Sprintf("%s%v", cacheChaozjTagIdPrefix, id)
	var resp Tag
	err := m.QueryRowCtx(ctx, &resp, chaozjTagIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tagRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTagModel) Insert(ctx context.Context, data *Tag) (sql.Result, error) {
	chaozjTagIdKey := fmt.Sprintf("%s%v", cacheChaozjTagIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, tagRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TagName, data.TagDesc)
	}, chaozjTagIdKey)
	return ret, err
}

func (m *defaultTagModel) Update(ctx context.Context, data *Tag) error {
	chaozjTagIdKey := fmt.Sprintf("%s%v", cacheChaozjTagIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tagRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TagName, data.TagDesc, data.Id)
	}, chaozjTagIdKey)
	return err
}

func (m *defaultTagModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheChaozjTagIdPrefix, primary)
}

func (m *defaultTagModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tagRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTagModel) tableName() string {
	return m.table
}
