// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package comment_metrics

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentMetricsFieldNames          = builder.RawFieldNames(&CommentMetrics{}, true)
	commentMetricsRows                = strings.Join(commentMetricsFieldNames, ",")
	commentMetricsRowsExpectAutoSet   = strings.Join(stringx.Remove(commentMetricsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	commentMetricsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(commentMetricsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	publicCommentMetricsIdPrefix        = ":public:commentMetrics:id:"
	publicCommentMetricsCommentIdPrefix = ":public:commentMetrics:commentId:"
)

type (
	commentMetricsModel interface {
		Insert(ctx context.Context, data *CommentMetrics) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CommentMetrics, error)
		FindOneByCommentId(ctx context.Context, commentId int64) (*CommentMetrics, error)
		Update(ctx context.Context, data *CommentMetrics) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCommentMetricsModel struct {
		sqlc.CachedConn
		table string
	}

	CommentMetrics struct {
		Id        int64 `db:"id"`
		CommentId int64 `db:"comment_id"` // 评论ID
		Likes     int64 `db:"likes"`      // 点赞数
		Comments  int64 `db:"comments"`   // 评论数
	}
)

func newCommentMetricsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCommentMetricsModel {
	return &defaultCommentMetricsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."comment_metrics"`,
	}
}

func (m *defaultCommentMetricsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	publicCommentMetricsCommentIdKey := fmt.Sprintf("%s%v", publicCommentMetricsCommentIdPrefix, data.CommentId)
	publicCommentMetricsIdKey := fmt.Sprintf("%s%v", publicCommentMetricsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicCommentMetricsCommentIdKey, publicCommentMetricsIdKey)
	return err
}

func (m *defaultCommentMetricsModel) FindOne(ctx context.Context, id int64) (*CommentMetrics, error) {
	publicCommentMetricsIdKey := fmt.Sprintf("%s%v", publicCommentMetricsIdPrefix, id)
	var resp CommentMetrics
	err := m.QueryRowCtx(ctx, &resp, publicCommentMetricsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", commentMetricsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentMetricsModel) FindOneByCommentId(ctx context.Context, commentId int64) (*CommentMetrics, error) {
	publicCommentMetricsCommentIdKey := fmt.Sprintf("%s%v", publicCommentMetricsCommentIdPrefix, commentId)
	var resp CommentMetrics
	err := m.QueryRowIndexCtx(ctx, &resp, publicCommentMetricsCommentIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where comment_id = $1 limit 1", commentMetricsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, commentId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentMetricsModel) Insert(ctx context.Context, data *CommentMetrics) (sql.Result, error) {
	publicCommentMetricsCommentIdKey := fmt.Sprintf("%s%v", publicCommentMetricsCommentIdPrefix, data.CommentId)
	publicCommentMetricsIdKey := fmt.Sprintf("%s%v", publicCommentMetricsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, commentMetricsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.CommentId, data.Likes, data.Comments)
	}, publicCommentMetricsCommentIdKey, publicCommentMetricsIdKey)
	return ret, err
}

func (m *defaultCommentMetricsModel) Update(ctx context.Context, newData *CommentMetrics) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	publicCommentMetricsCommentIdKey := fmt.Sprintf("%s%v", publicCommentMetricsCommentIdPrefix, data.CommentId)
	publicCommentMetricsIdKey := fmt.Sprintf("%s%v", publicCommentMetricsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, commentMetricsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.CommentId, newData.Likes, newData.Comments)
	}, publicCommentMetricsCommentIdKey, publicCommentMetricsIdKey)
	return err
}

func (m *defaultCommentMetricsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", publicCommentMetricsIdPrefix, primary)
}

func (m *defaultCommentMetricsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", commentMetricsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCommentMetricsModel) tableName() string {
	return m.table
}
