// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	adminfeed "zerobackend/internal/handler/adminfeed"
	adminuser "zerobackend/internal/handler/adminuser"
	comment "zerobackend/internal/handler/comment"
	feed "zerobackend/internal/handler/feed"
	follow "zerobackend/internal/handler/follow"
	home "zerobackend/internal/handler/home"
	report "zerobackend/internal/handler/report"
	test "zerobackend/internal/handler/test"
	upload "zerobackend/internal/handler/upload"
	user "zerobackend/internal/handler/user"
	"zerobackend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 封禁动态
				Method:  http.MethodPost,
				Path:    "/feed/ban",
				Handler: adminfeed.BanFeedHandler(serverCtx),
			},
			{
				// 解禁动态
				Method:  http.MethodPost,
				Path:    "/feed/unban",
				Handler: adminfeed.UnBanFeedHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 封禁用户
				Method:  http.MethodPost,
				Path:    "/user/ban",
				Handler: adminuser.BanUserHandler(serverCtx),
			},
			{
				// 改变用户权限
				Method:  http.MethodPost,
				Path:    "/user/changetype",
				Handler: adminuser.ChangeUserTypeHandler(serverCtx),
			},
			{
				// 解禁用户
				Method:  http.MethodPost,
				Path:    "/user/unban",
				Handler: adminuser.UnBanUserHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取评论列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: comment.GetCommentListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/comment"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 点赞评论
				Method:  http.MethodPost,
				Path:    "/like",
				Handler: comment.LikeCommentHandler(serverCtx),
			},
			{
				// 创建评论
				Method:  http.MethodPost,
				Path:    "/new",
				Handler: comment.NewCommentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/comment"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 帧（文章）详情
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: feed.GetFeedDetailHandler(serverCtx),
			},
		},
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/feed"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 删除帧（文章）
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: feed.DeleteFeedHandler(serverCtx),
			},
			{
				// 创建帧（文章）
				Method:  http.MethodPost,
				Path:    "/new",
				Handler: feed.NewFeedHandler(serverCtx),
			},
			{
				// 分享小红书帧（文章）
				Method:  http.MethodGet,
				Path:    "/share/xhs",
				Handler: feed.ShareFeedXHSHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/feed"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户的粉丝列表
				Method:  http.MethodGet,
				Path:    "/fansList",
				Handler: follow.GetFansListHandler(serverCtx),
			},
			{
				// 关注/取消关注用户
				Method:  http.MethodPost,
				Path:    "/follow",
				Handler: follow.FollowHandler(serverCtx),
			},
			{
				// 获取用户的关注列表
				Method:  http.MethodGet,
				Path:    "/followList",
				Handler: follow.GetFollowListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/follow"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取首页信息流
				Method:  http.MethodGet,
				Path:    "/getfeeds",
				Handler: home.GetIndexFeedsHandler(serverCtx),
			},
			{
				// 获取用户主页帖子
				Method:  http.MethodGet,
				Path:    "/userfeeds",
				Handler: home.UserFeedsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/home"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 举报
				Method:  http.MethodPost,
				Path:    "/new-report",
				Handler: report.ReportHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/report"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建帧（文章）
				Method:  http.MethodPost,
				Path:    "/normal",
				Handler: test.NormalTestHandler(serverCtx),
			},
		},
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/test"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取到上传token
				Method:  http.MethodGet,
				Path:    "/normal",
				Handler: upload.GetUpTokenHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/upload"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/:uid",
				Handler: user.UserInfoHandler(serverCtx),
			},
			{
				// uid账号登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 手机密码登录
				Method:  http.MethodPost,
				Path:    "/login-mobile-pass",
				Handler: user.LoginByMobilePassHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				// 获取验证码
				Method:  http.MethodPost,
				Path:    "/verify-code",
				Handler: user.VerifyCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 更改用户信息(token)
				Method:  http.MethodPost,
				Path:    "/change-info",
				Handler: user.ChangeUserInfoHandler(serverCtx),
			},
			{
				// 更改手机号码(token)
				Method:  http.MethodPost,
				Path:    "/change-mobile",
				Handler: user.ChangeMobileHandler(serverCtx),
			},
			{
				// 更改密码(token)
				Method:  http.MethodPost,
				Path:    "/change-password",
				Handler: user.ChangePasswordHandler(serverCtx),
			},
			{
				// 获取用户关注、收藏、点赞列表
				Method:  http.MethodGet,
				Path:    "/relation",
				Handler: user.UserRelationHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/user"),
	)
}
