// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	adminfeed "zerobackend/internal/handler/adminfeed"
	adminuser "zerobackend/internal/handler/adminuser"
	article "zerobackend/internal/handler/article"
	follow "zerobackend/internal/handler/follow"
	home "zerobackend/internal/handler/home"
	user "zerobackend/internal/handler/user"
	"zerobackend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 封禁动态
				Method:  http.MethodPost,
				Path:    "/feed/ban",
				Handler: adminfeed.BanFeedHandler(serverCtx),
			},
			{
				// 解禁动态
				Method:  http.MethodPost,
				Path:    "/feed/unban",
				Handler: adminfeed.UnBanFeedHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 封禁用户
				Method:  http.MethodPost,
				Path:    "/user/ban",
				Handler: adminuser.BanUserHandler(serverCtx),
			},
			{
				// 改变用户权限
				Method:  http.MethodPost,
				Path:    "/user/changetype",
				Handler: adminuser.ChangeFeedStatusHandler(serverCtx),
			},
			{
				// 解禁用户
				Method:  http.MethodPost,
				Path:    "/user/unban",
				Handler: adminuser.UnBanUserHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 删除帧（文章）
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: article.DeleteArticleHandler(serverCtx),
			},
			{
				// 创建帧（文章）
				Method:  http.MethodPost,
				Path:    "/new",
				Handler: article.NewArticleHandler(serverCtx),
			},
			{
				// 搜索帧（文章）
				Method:  http.MethodPost,
				Path:    "/search",
				Handler: article.SearchArticleHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/article"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户的粉丝列表
				Method:  http.MethodGet,
				Path:    "/fansList",
				Handler: follow.GetFansListHandler(serverCtx),
			},
			{
				// 关注/取消关注用户
				Method:  http.MethodPost,
				Path:    "/follow",
				Handler: follow.FollowHandler(serverCtx),
			},
			{
				// 获取用户的关注列表
				Method:  http.MethodGet,
				Path:    "/followList",
				Handler: follow.GetFollowListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/follow"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取首页信息流
				Method:  http.MethodPost,
				Path:    "/get-feeds",
				Handler: home.GetIndexFeedsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/home"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 更改手机号码
				Method:  http.MethodPost,
				Path:    "/change-mobile",
				Handler: user.ChangeMobileHandler(serverCtx),
			},
			{
				// uid账号登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 手机密码登录
				Method:  http.MethodPost,
				Path:    "/login-mobile-pass",
				Handler: user.LoginByMobilePassHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				// 获取验证码
				Method:  http.MethodPost,
				Path:    "/verify-code",
				Handler: user.VerifyCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 更改用户信息 需要token
				Method:  http.MethodPost,
				Path:    "/change-info",
				Handler: user.ChangeUserInfoHandler(serverCtx),
			},
			{
				// 更改密码 需要token
				Method:  http.MethodPost,
				Path:    "/change-password",
				Handler: user.ChangePasswordHandler(serverCtx),
			},
			{
				// 获取用户信息 需要token
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: user.UserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/user"),
	)
}
