// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package follow

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	followFieldNames          = builder.RawFieldNames(&Follow{})
	followRows                = strings.Join(followFieldNames, ",")
	followRowsExpectAutoSet   = strings.Join(stringx.Remove(followFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	followRowsWithPlaceHolder = strings.Join(stringx.Remove(followFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheChaozjFollowIdPrefix                   = "cache:chaozj:follow:id:"
	cacheChaozjFollowUserIdFollowedUserIdPrefix = "cache:chaozj:follow:userId:followedUserId:"
)

type (
	followModel interface {
		Insert(ctx context.Context, data *Follow) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Follow, error)
		FindOneByUserIdFollowedUserId(ctx context.Context, userId uint64, followedUserId uint64) (*Follow, error)
		Update(ctx context.Context, data *Follow) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFollowModel struct {
		sqlc.CachedConn
		table string
	}

	Follow struct {
		Id             uint64    `db:"id"`               // 主键ID
		UserId         uint64    `db:"user_id"`          // 用户ID
		FollowedUserId uint64    `db:"followed_user_id"` // 被关注用户ID
		FollowStatus   uint64    `db:"follow_status"`    // 关注状态：1-关注，2-取消关注
		CreateTime     time.Time `db:"create_time"`      // 创建时间
		UpdateTime     time.Time `db:"update_time"`      // 最后修改时间
	}
)

func newFollowModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFollowModel {
	return &defaultFollowModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`follow`",
	}
}

func (m *defaultFollowModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	chaozjFollowIdKey := fmt.Sprintf("%s%v", cacheChaozjFollowIdPrefix, id)
	chaozjFollowUserIdFollowedUserIdKey := fmt.Sprintf("%s%v:%v", cacheChaozjFollowUserIdFollowedUserIdPrefix, data.UserId, data.FollowedUserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, chaozjFollowIdKey, chaozjFollowUserIdFollowedUserIdKey)
	return err
}

func (m *defaultFollowModel) FindOne(ctx context.Context, id uint64) (*Follow, error) {
	chaozjFollowIdKey := fmt.Sprintf("%s%v", cacheChaozjFollowIdPrefix, id)
	var resp Follow
	err := m.QueryRowCtx(ctx, &resp, chaozjFollowIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", followRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowModel) FindOneByUserIdFollowedUserId(ctx context.Context, userId uint64, followedUserId uint64) (*Follow, error) {
	chaozjFollowUserIdFollowedUserIdKey := fmt.Sprintf("%s%v:%v", cacheChaozjFollowUserIdFollowedUserIdPrefix, userId, followedUserId)
	var resp Follow
	err := m.QueryRowIndexCtx(ctx, &resp, chaozjFollowUserIdFollowedUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `followed_user_id` = ? limit 1", followRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, followedUserId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowModel) Insert(ctx context.Context, data *Follow) (sql.Result, error) {
	chaozjFollowIdKey := fmt.Sprintf("%s%v", cacheChaozjFollowIdPrefix, data.Id)
	chaozjFollowUserIdFollowedUserIdKey := fmt.Sprintf("%s%v:%v", cacheChaozjFollowUserIdFollowedUserIdPrefix, data.UserId, data.FollowedUserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, followRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FollowedUserId, data.FollowStatus)
	}, chaozjFollowIdKey, chaozjFollowUserIdFollowedUserIdKey)
	return ret, err
}

func (m *defaultFollowModel) Update(ctx context.Context, newData *Follow) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	chaozjFollowIdKey := fmt.Sprintf("%s%v", cacheChaozjFollowIdPrefix, data.Id)
	chaozjFollowUserIdFollowedUserIdKey := fmt.Sprintf("%s%v:%v", cacheChaozjFollowUserIdFollowedUserIdPrefix, data.UserId, data.FollowedUserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, followRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.FollowedUserId, newData.FollowStatus, newData.Id)
	}, chaozjFollowIdKey, chaozjFollowUserIdFollowedUserIdKey)
	return err
}

func (m *defaultFollowModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheChaozjFollowIdPrefix, primary)
}

func (m *defaultFollowModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", followRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFollowModel) tableName() string {
	return m.table
}
