// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.6

package article

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articleFieldNames          = builder.RawFieldNames(&Article{}, true)
	articleRows                = strings.Join(articleFieldNames, ",")
	articleRowsExpectAutoSet   = strings.Join(stringx.Remove(articleFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	articleRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(articleFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicArticleIdPrefix = "cache:public:article:id:"
)

type (
	articleModel interface {
		Insert(ctx context.Context, data *Article) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Article, error)
		Update(ctx context.Context, data *Article) error
		Delete(ctx context.Context, id int64) error
	}

	defaultArticleModel struct {
		sqlc.CachedConn
		table string
	}

	Article struct {
		Id          int64     `db:"id"`           // 主键ID
		Title       string    `db:"title"`        // 标题
		Content     string    `db:"content"`      // 原始文本
		RawContent  string    `db:"raw_content"`  // 内容
		AuthorId    int64     `db:"author_id"`    // 作者ID
		Status      int64     `db:"status"`       // 状态 0:正常 1:仅自己 2:删除
		Type        int64     `db:"type"`         // 状态 0:默认图片帧 1:视频帧 2:纯文字帧
		IpLocation  string    `db:"ip_location"`  // IP归属地
		PublishTime time.Time `db:"publish_time"` // 发布时间
		CreateTime  time.Time `db:"create_time"`  // 创建时间
		UpdateTime  time.Time `db:"update_time"`  // 最后修改时间
		AiInsp      int64     `db:"ai_insp"`      // AI检验，默认0没有问题，1出现问题。
		Insp        int64     `db:"insp"`         // 人工校验为0时可用，默认为1待检验
	}
)

func newArticleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultArticleModel {
	return &defaultArticleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."article"`,
	}
}

func (m *defaultArticleModel) Delete(ctx context.Context, id int64) error {
	publicArticleIdKey := fmt.Sprintf("%s%v", cachePublicArticleIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicArticleIdKey)
	return err
}

func (m *defaultArticleModel) FindOne(ctx context.Context, id int64) (*Article, error) {
	publicArticleIdKey := fmt.Sprintf("%s%v", cachePublicArticleIdPrefix, id)
	var resp Article
	err := m.QueryRowCtx(ctx, &resp, publicArticleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", articleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleModel) Insert(ctx context.Context, data *Article) (sql.Result, error) {
	publicArticleIdKey := fmt.Sprintf("%s%v", cachePublicArticleIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, articleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Title, data.Content, data.RawContent, data.AuthorId, data.Status, data.Type, data.IpLocation, data.PublishTime, data.AiInsp, data.Insp)
	}, publicArticleIdKey)
	return ret, err
}

func (m *defaultArticleModel) Update(ctx context.Context, data *Article) error {
	publicArticleIdKey := fmt.Sprintf("%s%v", cachePublicArticleIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, articleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.Title, data.Content, data.RawContent, data.AuthorId, data.Status, data.Type, data.IpLocation, data.PublishTime, data.AiInsp, data.Insp)
	}, publicArticleIdKey)
	return err
}

func (m *defaultArticleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicArticleIdPrefix, primary)
}

func (m *defaultArticleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", articleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultArticleModel) tableName() string {
	return m.table
}
