// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package wiki_history

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	wikiHistoryFieldNames          = builder.RawFieldNames(&WikiHistory{}, true)
	wikiHistoryRows                = strings.Join(wikiHistoryFieldNames, ",")
	wikiHistoryRowsExpectAutoSet   = strings.Join(stringx.Remove(wikiHistoryFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	wikiHistoryRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(wikiHistoryFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	publicWikiHistoryIdPrefix = ":public:wikiHistory:id:"
)

type (
	wikiHistoryModel interface {
		Insert(ctx context.Context, data *WikiHistory) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WikiHistory, error)
		Update(ctx context.Context, data *WikiHistory) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWikiHistoryModel struct {
		sqlc.CachedConn
		table string
	}

	WikiHistory struct {
		Id         int64          `db:"id"`
		WikiId     int64          `db:"wiki_id"`
		RawContent sql.NullString `db:"raw_content"`
		EditorId   int64          `db:"editor_id"`
		EditTime   time.Time      `db:"edit_time"`
		ChangeLog  sql.NullString `db:"change_log"`
	}
)

func newWikiHistoryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWikiHistoryModel {
	return &defaultWikiHistoryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."wiki_history"`,
	}
}

func (m *defaultWikiHistoryModel) Delete(ctx context.Context, id int64) error {
	publicWikiHistoryIdKey := fmt.Sprintf("%s%v", publicWikiHistoryIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicWikiHistoryIdKey)
	return err
}

func (m *defaultWikiHistoryModel) FindOne(ctx context.Context, id int64) (*WikiHistory, error) {
	publicWikiHistoryIdKey := fmt.Sprintf("%s%v", publicWikiHistoryIdPrefix, id)
	var resp WikiHistory
	err := m.QueryRowCtx(ctx, &resp, publicWikiHistoryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", wikiHistoryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWikiHistoryModel) Insert(ctx context.Context, data *WikiHistory) (sql.Result, error) {
	publicWikiHistoryIdKey := fmt.Sprintf("%s%v", publicWikiHistoryIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, wikiHistoryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.WikiId, data.RawContent, data.EditorId, data.EditTime, data.ChangeLog)
	}, publicWikiHistoryIdKey)
	return ret, err
}

func (m *defaultWikiHistoryModel) Update(ctx context.Context, data *WikiHistory) error {
	publicWikiHistoryIdKey := fmt.Sprintf("%s%v", publicWikiHistoryIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, wikiHistoryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.WikiId, data.RawContent, data.EditorId, data.EditTime, data.ChangeLog)
	}, publicWikiHistoryIdKey)
	return err
}

func (m *defaultWikiHistoryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", publicWikiHistoryIdPrefix, primary)
}

func (m *defaultWikiHistoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", wikiHistoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWikiHistoryModel) tableName() string {
	return m.table
}
