// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package wiki

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	wikiFieldNames          = builder.RawFieldNames(&Wiki{}, true)
	wikiRows                = strings.Join(wikiFieldNames, ",")
	wikiRowsExpectAutoSet   = strings.Join(stringx.Remove(wikiFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	wikiRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(wikiFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	publicWikiIdPrefix = ":public:wiki:id:"
)

type (
	wikiModel interface {
		Insert(ctx context.Context, data *Wiki) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Wiki, error)
		Update(ctx context.Context, data *Wiki) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWikiModel struct {
		sqlc.CachedConn
		table string
	}

	Wiki struct {
		Id         int64          `db:"id"`
		Type       sql.NullString `db:"type"`
		RawContent sql.NullString `db:"raw_content"`
		Content    sql.NullString `db:"content"`
		Editor     sql.NullString `db:"editor"`
		Status     sql.NullInt64  `db:"status"`
		Name       sql.NullString `db:"name"`
		CreateTime time.Time      `db:"create_time"`
		UpdateTime time.Time      `db:"update_time"`
	}
)

func newWikiModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWikiModel {
	return &defaultWikiModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."wiki"`,
	}
}

func (m *defaultWikiModel) Delete(ctx context.Context, id int64) error {
	publicWikiIdKey := fmt.Sprintf("%s%v", publicWikiIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicWikiIdKey)
	return err
}

func (m *defaultWikiModel) FindOne(ctx context.Context, id int64) (*Wiki, error) {
	publicWikiIdKey := fmt.Sprintf("%s%v", publicWikiIdPrefix, id)
	var resp Wiki
	err := m.QueryRowCtx(ctx, &resp, publicWikiIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", wikiRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWikiModel) Insert(ctx context.Context, data *Wiki) (sql.Result, error) {
	publicWikiIdKey := fmt.Sprintf("%s%v", publicWikiIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, wikiRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Type, data.RawContent, data.Content, data.Editor, data.Status, data.Name)
	}, publicWikiIdKey)
	return ret, err
}

func (m *defaultWikiModel) Update(ctx context.Context, data *Wiki) error {
	publicWikiIdKey := fmt.Sprintf("%s%v", publicWikiIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, wikiRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.Type, data.RawContent, data.Content, data.Editor, data.Status, data.Name)
	}, publicWikiIdKey)
	return err
}

func (m *defaultWikiModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", publicWikiIdPrefix, primary)
}

func (m *defaultWikiModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", wikiRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWikiModel) tableName() string {
	return m.table
}
