// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package collect

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	collectFieldNames          = builder.RawFieldNames(&Collect{})
	collectRows                = strings.Join(collectFieldNames, ",")
	collectRowsExpectAutoSet   = strings.Join(stringx.Remove(collectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	collectRowsWithPlaceHolder = strings.Join(stringx.Remove(collectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheChaozjCollectIdPrefix                    = "cache:keyframe:collect:id:"
	cacheChaozjCollectUserIdCollectedFeedIdPrefix = "cache:keyframe:collect:userId:collectedFeedId:"
)

type (
	collectModel interface {
		Insert(ctx context.Context, data *Collect) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Collect, error)
		FindOneByUserIdCollectedFeedId(ctx context.Context, userId uint64, collectedFeedId uint64) (*Collect, error)
		Update(ctx context.Context, data *Collect) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCollectModel struct {
		sqlc.CachedConn
		table string
	}

	Collect struct {
		Id              uint64    `db:"id"`                // 主键ID
		UserId          uint64    `db:"user_id"`           // 用户ID
		CollectedFeedId uint64    `db:"collected_feed_id"` // 被收藏帖子ID
		FollowStatus    uint64    `db:"follow_status"`     // 关注状态：1-关注，2-取消关注
		CreateTime      time.Time `db:"create_time"`       // 创建时间
		UpdateTime      time.Time `db:"update_time"`       // 最后修改时间
	}
)

func newCollectModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCollectModel {
	return &defaultCollectModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`collect`",
	}
}

func (m *defaultCollectModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	chaozjCollectIdKey := fmt.Sprintf("%s%v", cacheChaozjCollectIdPrefix, id)
	chaozjCollectUserIdCollectedFeedIdKey := fmt.Sprintf("%s%v:%v", cacheChaozjCollectUserIdCollectedFeedIdPrefix, data.UserId, data.CollectedFeedId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, chaozjCollectIdKey, chaozjCollectUserIdCollectedFeedIdKey)
	return err
}

func (m *defaultCollectModel) FindOne(ctx context.Context, id uint64) (*Collect, error) {
	chaozjCollectIdKey := fmt.Sprintf("%s%v", cacheChaozjCollectIdPrefix, id)
	var resp Collect
	err := m.QueryRowCtx(ctx, &resp, chaozjCollectIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", collectRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollectModel) FindOneByUserIdCollectedFeedId(ctx context.Context, userId uint64, collectedFeedId uint64) (*Collect, error) {
	chaozjCollectUserIdCollectedFeedIdKey := fmt.Sprintf("%s%v:%v", cacheChaozjCollectUserIdCollectedFeedIdPrefix, userId, collectedFeedId)
	var resp Collect
	err := m.QueryRowIndexCtx(ctx, &resp, chaozjCollectUserIdCollectedFeedIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `collected_feed_id` = ? limit 1", collectRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, collectedFeedId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollectModel) Insert(ctx context.Context, data *Collect) (sql.Result, error) {
	chaozjCollectIdKey := fmt.Sprintf("%s%v", cacheChaozjCollectIdPrefix, data.Id)
	chaozjCollectUserIdCollectedFeedIdKey := fmt.Sprintf("%s%v:%v", cacheChaozjCollectUserIdCollectedFeedIdPrefix, data.UserId, data.CollectedFeedId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, collectRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.CollectedFeedId, data.FollowStatus)
	}, chaozjCollectIdKey, chaozjCollectUserIdCollectedFeedIdKey)
	return ret, err
}

func (m *defaultCollectModel) Update(ctx context.Context, newData *Collect) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	chaozjCollectIdKey := fmt.Sprintf("%s%v", cacheChaozjCollectIdPrefix, data.Id)
	chaozjCollectUserIdCollectedFeedIdKey := fmt.Sprintf("%s%v:%v", cacheChaozjCollectUserIdCollectedFeedIdPrefix, data.UserId, data.CollectedFeedId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, collectRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.CollectedFeedId, newData.FollowStatus, newData.Id)
	}, chaozjCollectIdKey, chaozjCollectUserIdCollectedFeedIdKey)
	return err
}

func (m *defaultCollectModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheChaozjCollectIdPrefix, primary)
}

func (m *defaultCollectModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", collectRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCollectModel) tableName() string {
	return m.table
}
