// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.6

package user_follow

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFollowFieldNames          = builder.RawFieldNames(&UserFollow{})
	userFollowRows                = strings.Join(userFollowFieldNames, ",")
	userFollowRowsExpectAutoSet   = strings.Join(stringx.Remove(userFollowFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userFollowRowsWithPlaceHolder = strings.Join(stringx.Remove(userFollowFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKeyframeUserFollowIdPrefix                   = "cache:keyframe:userFollow:id:"
	cacheKeyframeUserFollowUserIdFollowedUserIdPrefix = "cache:keyframe:userFollow:userId:followedUserId:"
)

type (
	userFollowModel interface {
		Insert(ctx context.Context, data *UserFollow) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserFollow, error)
		FindOneByUserIdFollowedUserId(ctx context.Context, userId uint64, followedUserId uint64) (*UserFollow, error)
		Update(ctx context.Context, data *UserFollow) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserFollowModel struct {
		sqlc.CachedConn
		table string
	}

	UserFollow struct {
		Id             uint64    `db:"id"`
		UserId         uint64    `db:"user_id"`          // 关注者ID
		FollowedUserId uint64    `db:"followed_user_id"` // 被关注用户ID
		Status         int64     `db:"status"`           // 状态：1-关注，0-取消
		CreateTime     time.Time `db:"create_time"`
		UpdateTime     time.Time `db:"update_time"`
	}
)

func newUserFollowModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserFollowModel {
	return &defaultUserFollowModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_follow`",
	}
}

func (m *defaultUserFollowModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	keyframeUserFollowIdKey := fmt.Sprintf("%s%v", cacheKeyframeUserFollowIdPrefix, id)
	keyframeUserFollowUserIdFollowedUserIdKey := fmt.Sprintf("%s%v:%v", cacheKeyframeUserFollowUserIdFollowedUserIdPrefix, data.UserId, data.FollowedUserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, keyframeUserFollowIdKey, keyframeUserFollowUserIdFollowedUserIdKey)
	return err
}

func (m *defaultUserFollowModel) FindOne(ctx context.Context, id uint64) (*UserFollow, error) {
	keyframeUserFollowIdKey := fmt.Sprintf("%s%v", cacheKeyframeUserFollowIdPrefix, id)
	var resp UserFollow
	err := m.QueryRowCtx(ctx, &resp, keyframeUserFollowIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userFollowRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserFollowModel) FindOneByUserIdFollowedUserId(ctx context.Context, userId uint64, followedUserId uint64) (*UserFollow, error) {
	keyframeUserFollowUserIdFollowedUserIdKey := fmt.Sprintf("%s%v:%v", cacheKeyframeUserFollowUserIdFollowedUserIdPrefix, userId, followedUserId)
	var resp UserFollow
	err := m.QueryRowIndexCtx(ctx, &resp, keyframeUserFollowUserIdFollowedUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `followed_user_id` = ? limit 1", userFollowRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, followedUserId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserFollowModel) Insert(ctx context.Context, data *UserFollow) (sql.Result, error) {
	keyframeUserFollowIdKey := fmt.Sprintf("%s%v", cacheKeyframeUserFollowIdPrefix, data.Id)
	keyframeUserFollowUserIdFollowedUserIdKey := fmt.Sprintf("%s%v:%v", cacheKeyframeUserFollowUserIdFollowedUserIdPrefix, data.UserId, data.FollowedUserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userFollowRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FollowedUserId, data.Status)
	}, keyframeUserFollowIdKey, keyframeUserFollowUserIdFollowedUserIdKey)
	return ret, err
}

func (m *defaultUserFollowModel) Update(ctx context.Context, newData *UserFollow) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	keyframeUserFollowIdKey := fmt.Sprintf("%s%v", cacheKeyframeUserFollowIdPrefix, data.Id)
	keyframeUserFollowUserIdFollowedUserIdKey := fmt.Sprintf("%s%v:%v", cacheKeyframeUserFollowUserIdFollowedUserIdPrefix, data.UserId, data.FollowedUserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userFollowRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.FollowedUserId, newData.Status, newData.Id)
	}, keyframeUserFollowIdKey, keyframeUserFollowUserIdFollowedUserIdKey)
	return err
}

func (m *defaultUserFollowModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKeyframeUserFollowIdPrefix, primary)
}

func (m *defaultUserFollowModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userFollowRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserFollowModel) tableName() string {
	return m.table
}
