// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package reply_count

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	replyCountFieldNames          = builder.RawFieldNames(&ReplyCount{})
	replyCountRows                = strings.Join(replyCountFieldNames, ",")
	replyCountRowsExpectAutoSet   = strings.Join(stringx.Remove(replyCountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	replyCountRowsWithPlaceHolder = strings.Join(stringx.Remove(replyCountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheChaozjReplyCountIdPrefix = "cache:chaozj:replyCount:id:"
)

type (
	replyCountModel interface {
		Insert(ctx context.Context, data *ReplyCount) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ReplyCount, error)
		Update(ctx context.Context, data *ReplyCount) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultReplyCountModel struct {
		sqlc.CachedConn
		table string
	}

	ReplyCount struct {
		Id           uint64    `db:"id"`             // 主键ID
		BizId        string    `db:"biz_id"`         // 业务ID
		TargetId     uint64    `db:"target_id"`      // 评论目标id
		ReplyNum     int64     `db:"reply_num"`      // 评论总数
		ReplyRootNum int64     `db:"reply_root_num"` // 根评论总数
		CreateTime   time.Time `db:"create_time"`    // 创建时间
		UpdateTime   time.Time `db:"update_time"`    // 最后修改时间
	}
)

func newReplyCountModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultReplyCountModel {
	return &defaultReplyCountModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`reply_count`",
	}
}

func (m *defaultReplyCountModel) Delete(ctx context.Context, id uint64) error {
	chaozjReplyCountIdKey := fmt.Sprintf("%s%v", cacheChaozjReplyCountIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, chaozjReplyCountIdKey)
	return err
}

func (m *defaultReplyCountModel) FindOne(ctx context.Context, id uint64) (*ReplyCount, error) {
	chaozjReplyCountIdKey := fmt.Sprintf("%s%v", cacheChaozjReplyCountIdPrefix, id)
	var resp ReplyCount
	err := m.QueryRowCtx(ctx, &resp, chaozjReplyCountIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", replyCountRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReplyCountModel) Insert(ctx context.Context, data *ReplyCount) (sql.Result, error) {
	chaozjReplyCountIdKey := fmt.Sprintf("%s%v", cacheChaozjReplyCountIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, replyCountRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.BizId, data.TargetId, data.ReplyNum, data.ReplyRootNum)
	}, chaozjReplyCountIdKey)
	return ret, err
}

func (m *defaultReplyCountModel) Update(ctx context.Context, data *ReplyCount) error {
	chaozjReplyCountIdKey := fmt.Sprintf("%s%v", cacheChaozjReplyCountIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, replyCountRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.BizId, data.TargetId, data.ReplyNum, data.ReplyRootNum, data.Id)
	}, chaozjReplyCountIdKey)
	return err
}

func (m *defaultReplyCountModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheChaozjReplyCountIdPrefix, primary)
}

func (m *defaultReplyCountModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", replyCountRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultReplyCountModel) tableName() string {
	return m.table
}
