// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package article_metrics

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articleMetricsFieldNames          = builder.RawFieldNames(&ArticleMetrics{}, true)
	articleMetricsRows                = strings.Join(articleMetricsFieldNames, ",")
	articleMetricsRowsExpectAutoSet   = strings.Join(stringx.Remove(articleMetricsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	articleMetricsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(articleMetricsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	publicArticleMetricsIdPrefix        = ":public:articleMetrics:id:"
	publicArticleMetricsArticleIdPrefix = ":public:articleMetrics:articleId:"
)

type (
	articleMetricsModel interface {
		Insert(ctx context.Context, data *ArticleMetrics) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ArticleMetrics, error)
		FindOneByArticleId(ctx context.Context, articleId int64) (*ArticleMetrics, error)
		Update(ctx context.Context, data *ArticleMetrics) error
		Delete(ctx context.Context, id int64) error
	}

	defaultArticleMetricsModel struct {
		sqlc.CachedConn
		table string
	}

	ArticleMetrics struct {
		Id        int64 `db:"id"`
		ArticleId int64 `db:"article_id"` // 文章ID
		Likes     int64 `db:"likes"`      // 点赞数
		Collects  int64 `db:"collects"`   // 收藏数
		Comments  int64 `db:"comments"`   // 评论数
		Shares    int64 `db:"shares"`     // 分享数
	}
)

func newArticleMetricsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultArticleMetricsModel {
	return &defaultArticleMetricsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."article_metrics"`,
	}
}

func (m *defaultArticleMetricsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	publicArticleMetricsArticleIdKey := fmt.Sprintf("%s%v", publicArticleMetricsArticleIdPrefix, data.ArticleId)
	publicArticleMetricsIdKey := fmt.Sprintf("%s%v", publicArticleMetricsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicArticleMetricsArticleIdKey, publicArticleMetricsIdKey)
	return err
}

func (m *defaultArticleMetricsModel) FindOne(ctx context.Context, id int64) (*ArticleMetrics, error) {
	publicArticleMetricsIdKey := fmt.Sprintf("%s%v", publicArticleMetricsIdPrefix, id)
	var resp ArticleMetrics
	err := m.QueryRowCtx(ctx, &resp, publicArticleMetricsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", articleMetricsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleMetricsModel) FindOneByArticleId(ctx context.Context, articleId int64) (*ArticleMetrics, error) {
	publicArticleMetricsArticleIdKey := fmt.Sprintf("%s%v", publicArticleMetricsArticleIdPrefix, articleId)
	var resp ArticleMetrics
	err := m.QueryRowIndexCtx(ctx, &resp, publicArticleMetricsArticleIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where article_id = $1 limit 1", articleMetricsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, articleId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleMetricsModel) Insert(ctx context.Context, data *ArticleMetrics) (sql.Result, error) {
	publicArticleMetricsArticleIdKey := fmt.Sprintf("%s%v", publicArticleMetricsArticleIdPrefix, data.ArticleId)
	publicArticleMetricsIdKey := fmt.Sprintf("%s%v", publicArticleMetricsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, articleMetricsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ArticleId, data.Likes, data.Collects, data.Comments, data.Shares)
	}, publicArticleMetricsArticleIdKey, publicArticleMetricsIdKey)
	return ret, err
}

func (m *defaultArticleMetricsModel) Update(ctx context.Context, newData *ArticleMetrics) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	publicArticleMetricsArticleIdKey := fmt.Sprintf("%s%v", publicArticleMetricsArticleIdPrefix, data.ArticleId)
	publicArticleMetricsIdKey := fmt.Sprintf("%s%v", publicArticleMetricsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, articleMetricsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.ArticleId, newData.Likes, newData.Collects, newData.Comments, newData.Shares)
	}, publicArticleMetricsArticleIdKey, publicArticleMetricsIdKey)
	return err
}

func (m *defaultArticleMetricsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", publicArticleMetricsIdPrefix, primary)
}

func (m *defaultArticleMetricsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", articleMetricsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultArticleMetricsModel) tableName() string {
	return m.table
}
