// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package follow_count

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	followCountFieldNames          = builder.RawFieldNames(&FollowCount{})
	followCountRows                = strings.Join(followCountFieldNames, ",")
	followCountRowsExpectAutoSet   = strings.Join(stringx.Remove(followCountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	followCountRowsWithPlaceHolder = strings.Join(stringx.Remove(followCountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheChaozjFollowCountIdPrefix     = "cache:chaozj:followCount:id:"
	cacheChaozjFollowCountUserIdPrefix = "cache:chaozj:followCount:userId:"
)

type (
	followCountModel interface {
		Insert(ctx context.Context, data *FollowCount) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*FollowCount, error)
		FindOneByUserId(ctx context.Context, userId uint64) (*FollowCount, error)
		Update(ctx context.Context, data *FollowCount) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFollowCountModel struct {
		sqlc.CachedConn
		table string
	}

	FollowCount struct {
		Id          uint64    `db:"id"`           // 主键ID
		UserId      uint64    `db:"user_id"`      // 用户ID
		FollowCount uint64    `db:"follow_count"` // 关注数
		FansCount   uint64    `db:"fans_count"`   // 粉丝数
		CreateTime  time.Time `db:"create_time"`  // 创建时间
		UpdateTime  time.Time `db:"update_time"`  // 最后修改时间
	}
)

func newFollowCountModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFollowCountModel {
	return &defaultFollowCountModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`follow_count`",
	}
}

func (m *defaultFollowCountModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	chaozjFollowCountIdKey := fmt.Sprintf("%s%v", cacheChaozjFollowCountIdPrefix, id)
	chaozjFollowCountUserIdKey := fmt.Sprintf("%s%v", cacheChaozjFollowCountUserIdPrefix, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, chaozjFollowCountIdKey, chaozjFollowCountUserIdKey)
	return err
}

func (m *defaultFollowCountModel) FindOne(ctx context.Context, id uint64) (*FollowCount, error) {
	chaozjFollowCountIdKey := fmt.Sprintf("%s%v", cacheChaozjFollowCountIdPrefix, id)
	var resp FollowCount
	err := m.QueryRowCtx(ctx, &resp, chaozjFollowCountIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", followCountRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowCountModel) FindOneByUserId(ctx context.Context, userId uint64) (*FollowCount, error) {
	chaozjFollowCountUserIdKey := fmt.Sprintf("%s%v", cacheChaozjFollowCountUserIdPrefix, userId)
	var resp FollowCount
	err := m.QueryRowIndexCtx(ctx, &resp, chaozjFollowCountUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", followCountRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowCountModel) Insert(ctx context.Context, data *FollowCount) (sql.Result, error) {
	chaozjFollowCountIdKey := fmt.Sprintf("%s%v", cacheChaozjFollowCountIdPrefix, data.Id)
	chaozjFollowCountUserIdKey := fmt.Sprintf("%s%v", cacheChaozjFollowCountUserIdPrefix, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, followCountRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FollowCount, data.FansCount)
	}, chaozjFollowCountIdKey, chaozjFollowCountUserIdKey)
	return ret, err
}

func (m *defaultFollowCountModel) Update(ctx context.Context, newData *FollowCount) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	chaozjFollowCountIdKey := fmt.Sprintf("%s%v", cacheChaozjFollowCountIdPrefix, data.Id)
	chaozjFollowCountUserIdKey := fmt.Sprintf("%s%v", cacheChaozjFollowCountUserIdPrefix, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, followCountRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.FollowCount, newData.FansCount, newData.Id)
	}, chaozjFollowCountIdKey, chaozjFollowCountUserIdKey)
	return err
}

func (m *defaultFollowCountModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheChaozjFollowCountIdPrefix, primary)
}

func (m *defaultFollowCountModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", followCountRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFollowCountModel) tableName() string {
	return m.table
}
