// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package media

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mediaFieldNames          = builder.RawFieldNames(&Media{})
	mediaRows                = strings.Join(mediaFieldNames, ",")
	mediaRowsExpectAutoSet   = strings.Join(stringx.Remove(mediaFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mediaRowsWithPlaceHolder = strings.Join(stringx.Remove(mediaFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheChaozjMediaIdPrefix = "cache:chaozj:media:id:"
)

type (
	mediaModel interface {
		Insert(ctx context.Context, data *Media) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Media, error)
		Update(ctx context.Context, data *Media) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMediaModel struct {
		sqlc.CachedConn
		table string
	}

	Media struct {
		Id        uint64         `db:"id"`
		ArticleId uint64         `db:"article_id"`
		CoverUrl  string         `db:"cover_url"`
		Height    int64          `db:"height"`
		Width     int64          `db:"width"`
		MediaList sql.NullString `db:"MediaList"`
	}
)

func newMediaModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMediaModel {
	return &defaultMediaModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`media`",
	}
}

func (m *defaultMediaModel) Delete(ctx context.Context, id uint64) error {
	chaozjMediaIdKey := fmt.Sprintf("%s%v", cacheChaozjMediaIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, chaozjMediaIdKey)
	return err
}

func (m *defaultMediaModel) FindOne(ctx context.Context, id uint64) (*Media, error) {
	chaozjMediaIdKey := fmt.Sprintf("%s%v", cacheChaozjMediaIdPrefix, id)
	var resp Media
	err := m.QueryRowCtx(ctx, &resp, chaozjMediaIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mediaRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaModel) Insert(ctx context.Context, data *Media) (sql.Result, error) {
	chaozjMediaIdKey := fmt.Sprintf("%s%v", cacheChaozjMediaIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, mediaRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ArticleId, data.CoverUrl, data.Height, data.Width, data.MediaList)
	}, chaozjMediaIdKey)
	return ret, err
}

func (m *defaultMediaModel) Update(ctx context.Context, data *Media) error {
	chaozjMediaIdKey := fmt.Sprintf("%s%v", cacheChaozjMediaIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mediaRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ArticleId, data.CoverUrl, data.Height, data.Width, data.MediaList, data.Id)
	}, chaozjMediaIdKey)
	return err
}

func (m *defaultMediaModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheChaozjMediaIdPrefix, primary)
}

func (m *defaultMediaModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mediaRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMediaModel) tableName() string {
	return m.table
}
