// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.6

package action_count

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	actionCountFieldNames          = builder.RawFieldNames(&ActionCount{}, true)
	actionCountRows                = strings.Join(actionCountFieldNames, ",")
	actionCountRowsExpectAutoSet   = strings.Join(stringx.Remove(actionCountFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	actionCountRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(actionCountFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicActionCountIdPrefix                 = "cache:public:actionCount:id:"
	cachePublicActionCountTargetIdTargetTypePrefix = "cache:public:actionCount:targetId:targetType:"
)

type (
	actionCountModel interface {
		Insert(ctx context.Context, data *ActionCount) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ActionCount, error)
		FindOneByTargetIdTargetType(ctx context.Context, targetId int64, targetType int64) (*ActionCount, error)
		Update(ctx context.Context, data *ActionCount) error
		Delete(ctx context.Context, id int64) error
	}

	defaultActionCountModel struct {
		sqlc.CachedConn
		table string
	}

	ActionCount struct {
		Id           int64     `db:"id"`            // 自增主键
		TargetId     int64     `db:"target_id"`     // 目标ID
		TargetType   int64     `db:"target_type"`   // 目标类型：1-文章, 2-评论, 3-用户
		LikeCount    int64     `db:"like_count"`    // 点赞数
		CollectCount int64     `db:"collect_count"` // 收藏数
		UpdateTime   time.Time `db:"update_time"`
	}
)

func newActionCountModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultActionCountModel {
	return &defaultActionCountModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."action_count"`,
	}
}

func (m *defaultActionCountModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	publicActionCountIdKey := fmt.Sprintf("%s%v", cachePublicActionCountIdPrefix, id)
	publicActionCountTargetIdTargetTypeKey := fmt.Sprintf("%s%v:%v", cachePublicActionCountTargetIdTargetTypePrefix, data.TargetId, data.TargetType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicActionCountIdKey, publicActionCountTargetIdTargetTypeKey)
	return err
}

func (m *defaultActionCountModel) FindOne(ctx context.Context, id int64) (*ActionCount, error) {
	publicActionCountIdKey := fmt.Sprintf("%s%v", cachePublicActionCountIdPrefix, id)
	var resp ActionCount
	err := m.QueryRowCtx(ctx, &resp, publicActionCountIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", actionCountRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultActionCountModel) FindOneByTargetIdTargetType(ctx context.Context, targetId int64, targetType int64) (*ActionCount, error) {
	publicActionCountTargetIdTargetTypeKey := fmt.Sprintf("%s%v:%v", cachePublicActionCountTargetIdTargetTypePrefix, targetId, targetType)
	var resp ActionCount
	err := m.QueryRowIndexCtx(ctx, &resp, publicActionCountTargetIdTargetTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where target_id = $1 and target_type = $2 limit 1", actionCountRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, targetId, targetType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultActionCountModel) Insert(ctx context.Context, data *ActionCount) (sql.Result, error) {
	publicActionCountIdKey := fmt.Sprintf("%s%v", cachePublicActionCountIdPrefix, data.Id)
	publicActionCountTargetIdTargetTypeKey := fmt.Sprintf("%s%v:%v", cachePublicActionCountTargetIdTargetTypePrefix, data.TargetId, data.TargetType)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, actionCountRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TargetId, data.TargetType, data.LikeCount, data.CollectCount)
	}, publicActionCountIdKey, publicActionCountTargetIdTargetTypeKey)
	return ret, err
}

func (m *defaultActionCountModel) Update(ctx context.Context, newData *ActionCount) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	publicActionCountIdKey := fmt.Sprintf("%s%v", cachePublicActionCountIdPrefix, data.Id)
	publicActionCountTargetIdTargetTypeKey := fmt.Sprintf("%s%v:%v", cachePublicActionCountTargetIdTargetTypePrefix, data.TargetId, data.TargetType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, actionCountRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.TargetId, newData.TargetType, newData.LikeCount, newData.CollectCount)
	}, publicActionCountIdKey, publicActionCountTargetIdTargetTypeKey)
	return err
}

func (m *defaultActionCountModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicActionCountIdPrefix, primary)
}

func (m *defaultActionCountModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", actionCountRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultActionCountModel) tableName() string {
	return m.table
}
