// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.6

package action_count

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	actionCountFieldNames          = builder.RawFieldNames(&ActionCount{})
	actionCountRows                = strings.Join(actionCountFieldNames, ",")
	actionCountRowsExpectAutoSet   = strings.Join(stringx.Remove(actionCountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	actionCountRowsWithPlaceHolder = strings.Join(stringx.Remove(actionCountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKeyframeActionCountIdPrefix                 = "cache:keyframe:actionCount:id:"
	cacheKeyframeActionCountTargetIdTargetTypePrefix = "cache:keyframe:actionCount:targetId:targetType:"
)

type (
	actionCountModel interface {
		Insert(ctx context.Context, data *ActionCount) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ActionCount, error)
		FindOneByTargetIdTargetType(ctx context.Context, targetId uint64, targetType int64) (*ActionCount, error)
		Update(ctx context.Context, data *ActionCount) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultActionCountModel struct {
		sqlc.CachedConn
		table string
	}

	ActionCount struct {
		Id           uint64    `db:"id"`            // 自增主键
		TargetId     uint64    `db:"target_id"`     // 目标ID
		TargetType   int64     `db:"target_type"`   // 目标类型：1-文章, 2-评论, 3-用户
		LikeCount    uint64    `db:"like_count"`    // 点赞数
		CollectCount uint64    `db:"collect_count"` // 收藏数
		UpdateTime   time.Time `db:"update_time"`
	}
)

func newActionCountModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultActionCountModel {
	return &defaultActionCountModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`action_count`",
	}
}

func (m *defaultActionCountModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	keyframeActionCountIdKey := fmt.Sprintf("%s%v", cacheKeyframeActionCountIdPrefix, id)
	keyframeActionCountTargetIdTargetTypeKey := fmt.Sprintf("%s%v:%v", cacheKeyframeActionCountTargetIdTargetTypePrefix, data.TargetId, data.TargetType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, keyframeActionCountIdKey, keyframeActionCountTargetIdTargetTypeKey)
	return err
}

func (m *defaultActionCountModel) FindOne(ctx context.Context, id uint64) (*ActionCount, error) {
	keyframeActionCountIdKey := fmt.Sprintf("%s%v", cacheKeyframeActionCountIdPrefix, id)
	var resp ActionCount
	err := m.QueryRowCtx(ctx, &resp, keyframeActionCountIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", actionCountRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultActionCountModel) FindOneByTargetIdTargetType(ctx context.Context, targetId uint64, targetType int64) (*ActionCount, error) {
	keyframeActionCountTargetIdTargetTypeKey := fmt.Sprintf("%s%v:%v", cacheKeyframeActionCountTargetIdTargetTypePrefix, targetId, targetType)
	var resp ActionCount
	err := m.QueryRowIndexCtx(ctx, &resp, keyframeActionCountTargetIdTargetTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `target_id` = ? and `target_type` = ? limit 1", actionCountRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, targetId, targetType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultActionCountModel) Insert(ctx context.Context, data *ActionCount) (sql.Result, error) {
	keyframeActionCountIdKey := fmt.Sprintf("%s%v", cacheKeyframeActionCountIdPrefix, data.Id)
	keyframeActionCountTargetIdTargetTypeKey := fmt.Sprintf("%s%v:%v", cacheKeyframeActionCountTargetIdTargetTypePrefix, data.TargetId, data.TargetType)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, actionCountRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TargetId, data.TargetType, data.LikeCount, data.CollectCount)
	}, keyframeActionCountIdKey, keyframeActionCountTargetIdTargetTypeKey)
	return ret, err
}

func (m *defaultActionCountModel) Update(ctx context.Context, newData *ActionCount) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	keyframeActionCountIdKey := fmt.Sprintf("%s%v", cacheKeyframeActionCountIdPrefix, data.Id)
	keyframeActionCountTargetIdTargetTypeKey := fmt.Sprintf("%s%v:%v", cacheKeyframeActionCountTargetIdTargetTypePrefix, data.TargetId, data.TargetType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, actionCountRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TargetId, newData.TargetType, newData.LikeCount, newData.CollectCount, newData.Id)
	}, keyframeActionCountIdKey, keyframeActionCountTargetIdTargetTypeKey)
	return err
}

func (m *defaultActionCountModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKeyframeActionCountIdPrefix, primary)
}

func (m *defaultActionCountModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", actionCountRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultActionCountModel) tableName() string {
	return m.table
}
