// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tagResourceFieldNames          = builder.RawFieldNames(&TagResource{})
	tagResourceRows                = strings.Join(tagResourceFieldNames, ",")
	tagResourceRowsExpectAutoSet   = strings.Join(stringx.Remove(tagResourceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tagResourceRowsWithPlaceHolder = strings.Join(stringx.Remove(tagResourceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheChaozjTagResourceIdPrefix = "cache:chaozj:tagResource:id:"
)

type (
	tagResourceModel interface {
		Insert(ctx context.Context, data *TagResource) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*TagResource, error)
		Update(ctx context.Context, data *TagResource) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTagResourceModel struct {
		sqlc.CachedConn
		table string
	}

	TagResource struct {
		Id         uint64    `db:"id"`          // 主键ID
		BizId      string    `db:"biz_id"`      // 业务ID
		TargetId   uint64    `db:"target_id"`   // 内容id
		TagId      uint64    `db:"tag_id"`      // 标签id
		UserId     uint64    `db:"user_id"`     // 用户ID
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 最后修改时间
	}
)

func newTagResourceModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTagResourceModel {
	return &defaultTagResourceModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tag_resource`",
	}
}

func (m *defaultTagResourceModel) Delete(ctx context.Context, id uint64) error {
	chaozjTagResourceIdKey := fmt.Sprintf("%s%v", cacheChaozjTagResourceIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, chaozjTagResourceIdKey)
	return err
}

func (m *defaultTagResourceModel) FindOne(ctx context.Context, id uint64) (*TagResource, error) {
	chaozjTagResourceIdKey := fmt.Sprintf("%s%v", cacheChaozjTagResourceIdPrefix, id)
	var resp TagResource
	err := m.QueryRowCtx(ctx, &resp, chaozjTagResourceIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tagResourceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTagResourceModel) Insert(ctx context.Context, data *TagResource) (sql.Result, error) {
	chaozjTagResourceIdKey := fmt.Sprintf("%s%v", cacheChaozjTagResourceIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, tagResourceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.BizId, data.TargetId, data.TagId, data.UserId)
	}, chaozjTagResourceIdKey)
	return ret, err
}

func (m *defaultTagResourceModel) Update(ctx context.Context, data *TagResource) error {
	chaozjTagResourceIdKey := fmt.Sprintf("%s%v", cacheChaozjTagResourceIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tagResourceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.BizId, data.TargetId, data.TagId, data.UserId, data.Id)
	}, chaozjTagResourceIdKey)
	return err
}

func (m *defaultTagResourceModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheChaozjTagResourceIdPrefix, primary)
}

func (m *defaultTagResourceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tagResourceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTagResourceModel) tableName() string {
	return m.table
}
